apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prom-http-sd.fullname" . }}
  labels:
    {{- include "prom-http-sd.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}
