---
name: Helm Lint

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types:
      - closed
    branches:
      - master

  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  helm_commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      - name: Run Helm Commands
        run: make lint-helm
